name: Build CLI

on:
  push:

run-name: Build from ${{ github.head_ref || github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false # suppress the noisy progress status output

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI
        run: go build .

      - name: Run unit tests
        run: go test ./...
