name: Metaplay CLI Latest Development Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-dev:
    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Delete old tag
        run: |
          git tag -d 0.0.0 || true
          git push origin :refs/tags/0.0.0 || true

      - name: Create new tag
        run: |
          git tag 0.0.0
          git push origin 0.0.0 --force

        # Dev builds are not published to distribution channels, only available in Github
      - name: Run GoReleaser (Nightly)
        uses: goreleaser/goreleaser-action@v6
        env:
          NIGHTLY: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          args: release --clean
