name: Metaplay CLI Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Tags must be available for GoReleaser, so fetch the full commit history
          show-progress: false # suppress the noisy progress status output

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Fetch tokens from the vault
        id: secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.int.metaplay.dev:8200
          path: github-actions
          role: ci-read
          method: jwt
          secrets: |
            metaplay/data/ci/metaplaybot-github metaplay_cli_release | METAPLAYBOT_GITHUB_TOKEN;
            metaplay/data/ci/metaplaybot-github chocolatey_api_key | METAPLAYBOT_CHOCO_API_KEY;

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          METAPLAYBOT_GITHUB_TOKEN: ${{ steps.secrets.outputs.METAPLAYBOT_GITHUB_TOKEN }}
          METAPLAYBOT_CHOCO_API_KEY: ${{ steps.secrets.outputs.METAPLAYBOT_CHOCO_API_KEY }}
        with:
          distribution: goreleaser
          args: release --clean

        # GoReleaser publishes the .nupkg, but we archive a copy in our private `choco-packages` repo
      - name: Archive Chocolatey artifacts
        env:
          CHOCOPKG_TOKEN: ${{ steps.secrets.outputs.METAPLAYBOT_GITHUB_TOKEN }}
        run: |
          git config user.email "info@metaplay.io"
          git config user.name "MetaplayBot"
          git clone "https://$CHOCOPKG_TOKEN@github.com/metaplay/choco-packages.git"
          cd choco-packages
          mkdir -p packages/metaplay/cli/
          copy ../dist\*.nupkg packages\metaplay\cli\  || echo "No .nupkg found"
          if exist ../dist\metaplay.choco (
            xcopy ../dist\metaplay.choco packages\metaplay\cli\ /E /I
          )

          # Stage & commit changes
          git add --all
          git diff-index --quiet HEAD || (
            git commit -m "Update metaplay choco artifacts for version ${GITHUB_REF##*/}"
            git push origin HEAD
          )
